import type { Category } from './types'

export const categories: Category[] = [
  {
    id: 'fundamentals',
    code: 'FM-01',
    title: '生存优先级',
    en: 'PRIORITIES',
    blurb: '先判断什么会在几小时内杀死你，再谈储备与技巧。',
    figure: 'threes',
  },
  {
    id: 'water',
    code: 'FM-02',
    title: '饮水与净化',
    en: 'WATER',
    blurb: '三天无水会迅速崩溃。找水、滤水、净水、煮沸、消毒、定量。',
    figure: 'water',
  },
  {
    id: 'food',
    code: 'FM-03',
    title: '食物与储备',
    en: 'RATIONS',
    blurb: '人可以挨饿数周，但不能靠未知野味赌命。',
    figure: 'kit',
  },
  {
    id: 'shelter',
    code: 'FM-04',
    title: '庇护与保暖',
    en: 'SHELTER',
    blurb: '失温比饥饿更快。选址、隔地、挡风、留出口。',
    figure: 'shelter',
  },
  {
    id: 'fire',
    code: 'FM-05',
    title: '火源与烹饪',
    en: 'FIRE',
    blurb: '火能消毒、取暖、发信号，也能烧掉你仅剩的营地。',
    figure: 'fire',
  },
  {
    id: 'medical',
    code: 'FM-06',
    title: '急救与医疗',
    en: 'MEDIC',
    blurb: '大出血、气道、低体温与中暑，是普通人最该先练的。',
    figure: 'bleed',
  },
  {
    id: 'hygiene',
    code: 'FM-07',
    title: '卫生与防疫',
    en: 'SANITATION',
    blurb: '灾难后真正的第二波往往是腹泻与感染。',
    figure: 'hygiene',
  },
  {
    id: 'signal',
    code: 'FM-08',
    title: '导航与求救',
    en: 'SIGNAL',
    blurb: '走得出去、被找得到，比多带三天口粮更重要。',
    figure: 'signal',
  },
  {
    id: 'urban',
    code: 'FM-09',
    title: '城市停摆',
    en: 'BLACKOUT',
    blurb: '停电、停水、停运才是多数人会遇到的「末日」。',
    figure: 'blackout',
  },
  {
    id: 'mind',
    code: 'FM-10',
    title: '心理与社群',
    en: 'MIND',
    blurb: '恐慌会耗尽判断。预案、角色、轮休比口号有用。',
    figure: 'mind',
  },
]
