import type { KitItem } from './types'

export const kitItems: KitItem[] = [
  { id: 'water', group: '水与食物', label: '每人每天 4 升水，至少 3 天', hint: '撤离按 3 天计，居家尽量备到 14 天。高温、孕妇、病人加量。', essential: true },
  { id: 'food', group: '水与食物', label: '无需冷藏的即食食物 3 天', hint: '罐头、能量棒、即食粥。另备开罐器。', essential: true },
  { id: 'can-opener', group: '水与食物', label: '手动开罐器', hint: '停电后电动工具失效。', essential: true },
  { id: 'bleach', group: '水与食物', label: '无香精家用漂白水', hint: '仅次氯酸钠 5–6%，用于消毒存水，不是喝原液。', essential: false },
  { id: 'filter', group: '水与食物', label: '便携滤水器或净化片', hint: '煮沸仍是金标准，滤芯是备份。', essential: false },
  { id: 'first-aid', group: '医疗', label: '家庭急救包', hint: '创可贴、纱布、胶带、消毒液、烫伤敷料。', essential: true },
  { id: 'trauma', group: '医疗', label: '止血带与加压绷带', hint: '先学会再装包。没练过的止血带可能无效。', essential: false },
  { id: 'meds', group: '医疗', label: '处方药至少 7 天', hint: '红十字建议居家尽量备到 1 个月，并写明剂量。', essential: true },
  { id: 'glasses', group: '医疗', label: '备用眼镜 / 助听器电池', hint: '灾害中最容易被忽略的功能件。', essential: false },
  { id: 'light', group: '照明通讯', label: '手电筒或头灯 + 备用电池', hint: '头灯能腾出手处理伤口或做饭。', essential: true },
  { id: 'radio', group: '照明通讯', label: '手摇 / 电池收音机', hint: '手机基站可能先于电力恢复。先听官方广播。', essential: true },
  { id: 'walkie', group: '照明通讯', label: '对讲机（已对好信道）', hint: '近距离无基站联络。天线竖直，先听后说。', essential: false },
  { id: 'power', group: '照明通讯', label: '移动电源与充电线', hint: '关机保温电量，只在窗口期开机。', essential: true },
  { id: 'whistle', group: '照明通讯', label: '哨子', hint: '比喊叫更省体力，也更容易被搜救听到。', essential: true },
  { id: 'cash', group: '证件与钱', label: '少量现金', hint: 'POS 与手机支付可能同时失效。', essential: true },
  { id: 'docs', group: '证件与钱', label: '证件与保单复印件', hint: '密封袋装身份证、户口、保险、用药清单。', essential: true },
  { id: 'contacts', group: '证件与钱', label: '纸质紧急联系人卡', hint: '写清集合点、过敏史、血型（如已知）。', essential: true },
  { id: 'tool', group: '工具', label: '多功能工具或折叠刀', hint: '能剪、能撬、能开包装。', essential: true },
  { id: 'tape', group: '工具', label: '布基胶带 + 垃圾袋', hint: '封窗、接水、隔湿、简易坐垫。', essential: false },
  { id: 'cord', group: '工具', label: '伞绳 15 米', hint: '晾衣、固定雨布、做提手。', essential: false },
  { id: 'blanket', group: '保暖防护', label: '应急保温毯或薄睡袋', hint: '失温比饥饿更快。', essential: true },
  { id: 'clothes', group: '保暖防护', label: '换洗衣物与结实鞋', hint: '按季节：雨衣或保暖层。', essential: true },
  { id: 'mask', group: '保暖防护', label: 'N95 或医用口罩', hint: '粉尘、烟气、拥挤避难所都用得上。', essential: false },
  { id: 'hygiene', group: '卫生', label: '卫生用品与垃圾袋', hint: '湿纸巾、月经用品、牙膏、肥皂。', essential: true },
  { id: 'toilet', group: '卫生', label: '便携马桶袋或猫砂方案', hint: '停水后马桶不能当无限下水道。', essential: false },
  { id: 'kids', group: '家庭加项', label: '婴幼儿配方、纸尿裤、安抚物', hint: '按实际家庭成员增减。', essential: false },
  { id: 'pet', group: '家庭加项', label: '宠物粮与牵引绳', hint: '很多避难点不接收无准备的宠物。', essential: false },
]
